const Historia= () =>{
    return(
        <div style={{textAlign:'left',}}className='p-3'>
            <h2>Historia</h2>
            Tilan perusti uudisraivaaja Jouko Jokula vuonna 1625. Jokula oli kotoisin jostain päin Etelä-Suomea.
            Hän päätyi uudisraivaajaksi kuninkaan uudisraivaajille myöntämien verohelpotusten myötä. Jokula lunasti 
            itselleen noin 1000ha tilan Itä-Suomesta. Aikojen saatossa tilasta on lohkottu muita tiloja ja maita on
            myyty toisille tiloille. Nykyisellä tilalla on vain 40ha metsää ja 10ha peltoa.
            <br/><br/>

            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, enim nec ultricies pharetra, tortor est vestibulum ante, in dictum diam urna eget sapien. Nullam odio purus, lacinia et nisi in, dapibus sagittis eros. Ut semper dui sed congue malesuada. Praesent at semper lorem, at efficitur turpis. Integer egestas ligula felis, a venenatis massa placerat nec. Vivamus non justo ac massa rutrum bibendum. Nullam hendrerit erat eget diam ullamcorper posuere.

Maecenas elementum, nisl mattis sodales sollicitudin, ipsum dui ultrices risus, ac facilisis tortor risus vel mauris. Phasellus metus mi, accumsan ac elit quis, posuere fermentum augue. Morbi scelerisque tempor mauris, non blandit erat ultricies eget. Nullam non dolor ac neque mollis bibendum et vitae odio. Pellentesque imperdiet diam in quam blandit, non ullamcorper sem volutpat. Sed dignissim ultricies turpis sed sollicitudin. Ut sit amet purus ut sem iaculis scelerisque quis eget metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse eu luctus ante. Integer at fringilla velit, a facilisis nisi. Phasellus feugiat, augue luctus ullamcorper eleifend, erat sem venenatis tortor, ac tempor orci ex blandit dolor. Aenean sit amet ipsum enim. Nam a vulputate mi. Aliquam venenatis nisi massa, a viverra elit tempus ac. Proin lorem massa, tincidunt in vulputate id, efficitur quis lectus.

In finibus lobortis ex ac tristique. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. <br/><br/> In hac habitasse platea dictumst. Nam tincidunt elit luctus quam rhoncus vehicula. In aliquam bibendum mi, a egestas ipsum porta id. In hac habitasse platea dictumst. Curabitur congue orci id libero aliquam ullamcorper. Praesent quis neque feugiat, elementum orci nec, luctus enim. In sed lorem vehicula, fermentum nunc et, scelerisque leo. Proin molestie risus non nulla ornare mattis in sed sem.

Quisque felis elit, sagittis ac tellus eu, porttitor sagittis lorem. Sed pharetra vehicula sapien, eget gravida augue tempus vel. Curabitur eu leo at nunc viverra placerat eleifend ut nisl. Vivamus tincidunt leo a hendrerit sodales. Nunc consequat vulputate aliquam. Vestibulum tempor venenatis risus. Vestibulum viverra auctor magna vel pharetra. Vivamus blandit felis eget aliquam volutpat. Aenean ultrices diam ligula, vitae pellentesque nunc sollicitudin sed. Aliquam erat volutpat. Donec posuere neque sollicitudin rhoncus cursus. Pellentesque congue a nisl ac bibendum. Nullam laoreet ante non elementum congue.

Duis eget diam congue, placerat tellus at, faucibus erat. Curabitur et imperdiet nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non fringilla enim. Aenean in augue vel magna accumsan molestie. Pellentesque mattis tortor sed felis dignissim, id porttitor arcu volutpat. Aenean nec pretium arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam pellentesque finibus varius. Nullam blandit velit viverra diam fringilla, pretium accumsan purus porta. Praesent pulvinar erat id purus ullamcorper hendrerit.

Integer mauris nulla, aliquam sed mollis dignissim, suscipit vel urna. Nullam rutrum elit sit amet diam aliquam sollicitudin. <br/> <br/>In eu velit sed nibh sagittis pulvinar in in risus. Morbi ac fermentum magna. Etiam a accumsan tortor, vitae congue sem. Proin cursus sit amet nisl sed egestas. Fusce gravida tellus eu tincidunt convallis. Nullam imperdiet dolor velit, vitae tincidunt lacus auctor eget. Quisque sed pretium orci. Nullam a ex in est volutpat euismod at quis nunc.

Nulla dui est, ultricies sed aliquet id, pretium ac tortor. Proin molestie sodales orci, nec tincidunt eros rutrum quis. Curabitur rhoncus, odio finibus lacinia facilisis, leo dolor volutpat massa, ut pulvinar leo quam in mauris. Cras ligula dolor, imperdiet tincidunt sagittis sit amet, accumsan at tortor. Praesent hendrerit in enim vitae iaculis. Maecenas consequat efficitur velit vitae tincidunt. Etiam bibendum nisi vitae turpis rhoncus, vitae consequat velit euismod. Ut venenatis, diam in vulputate vestibulum, ligula eros auctor justo, fringilla auctor lectus justo vitae quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus auctor dolor quam, id porta nisi convallis consectetur. Praesent cursus leo arcu, sit amet elementum neque lobortis eu. Proin lobortis laoreet ligula in dictum. Curabitur sit amet nunc eget turpis efficitur sagittis at in lectus.

Etiam elementum cursus urna at porta.<br/><br/> Proin eu rhoncus lectus. Duis porta vel libero in iaculis. Mauris pretium risus ut magna vestibulum dictum. Duis mattis magna at dolor ullamcorper bibendum. Sed condimentum vel libero sit amet mollis. Integer et tristique augue. Vivamus sed tempor dui. Suspendisse ut mi posuere sapien tempus molestie sed sed libero. Ut id aliquam urna, nec fermentum lorem. Suspendisse faucibus viverra enim id faucibus. Curabitur eu purus suscipit, varius quam mollis, cursus lacus. Nam euismod fermentum lectus id venenatis. Donec velit purus, egestas eget ex quis, suscipit egestas nisi.

Quisque diam odio, facilisis non nunc eu, volutpat pulvinar velit. Donec purus mi, suscipit vel diam id, malesuada commodo lectus.<br/><br/> Aenean aliquet diam eu erat commodo consequat. Etiam suscipit, metus vel congue luctus, sem velit vehicula neque, congue fermentum libero dui a massa. Maecenas ligula quam, fringilla interdum mauris sit amet, posuere cursus diam. Fusce placerat diam sed semper ullamcorper. Phasellus eget maximus augue. Ut vitae venenatis ipsum. Nunc semper gravida erat, ut aliquet purus semper non. Duis tempor imperdiet nisl, eget consequat tortor pulvinar vel. Proin elementum vitae massa et hendrerit. Nullam lacinia malesuada massa nec pellentesque. Proin diam arcu, scelerisque a sodales eget, posuere at sem. Donec varius vulputate nunc nec commodo. Aliquam in erat mauris. Donec pharetra mauris purus.

Aliquam eu urna malesuada, aliquet ligula at, eleifend metus. In vestibulum velit sapien, id tincidunt lorem volutpat ac. Donec sed metus consequat, pharetra ipsum a, cursus ipsum. Donec semper quam id ligula fringilla convallis. In tincidunt a arcu ac pharetra. Nunc sollicitudin convallis augue, nec commodo dolor viverra id. Praesent malesuada risus a ipsum bibendum euismod. Ut ornare justo vitae odio tempus congue. Fusce maximus justo vel nisl aliquet, at auctor massa cursus. Etiam eget consequat diam. Sed ac rhoncus urna. Sed hendrerit nibh aliquam nulla dapibus rutrum. Praesent eget posuere odio. Nulla dignissim eleifend odio vel mollis. Sed cursus lorem suscipit, feugiat ligula eu, aliquam ante. Ut hendrerit ante eu viverra feugiat.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, enim nec ultricies pharetra, tortor est vestibulum ante, in dictum diam urna eget sapien. Nullam odio purus, lacinia et nisi in, dapibus sagittis eros. Ut semper dui sed congue malesuada. Praesent at semper lorem, at efficitur turpis. Integer egestas ligula felis, a venenatis massa placerat nec. Vivamus non justo ac massa rutrum bibendum. Nullam hendrerit erat eget diam ullamcorper posuere.

Maecenas elementum, nisl mattis sodales sollicitudin, ipsum dui ultrices risus, ac facilisis tortor risus vel mauris. Phasellus metus mi, accumsan ac elit quis, posuere fermentum augue. Morbi scelerisque tempor mauris, non blandit erat ultricies eget. Nullam non dolor ac neque mollis bibendum et vitae odio. Pellentesque imperdiet diam in quam blandit, non ullamcorper sem volutpat. Sed dignissim ultricies turpis sed sollicitudin. Ut sit amet purus ut sem iaculis scelerisque quis eget metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse eu luctus ante. Integer at fringilla velit, a facilisis nisi. Phasellus feugiat, augue luctus ullamcorper eleifend, erat sem venenatis tortor, ac tempor orci ex blandit dolor. Aenean sit amet ipsum enim. Nam a vulputate mi. Aliquam venenatis nisi massa, a viverra elit tempus ac. Proin lorem massa, tincidunt in vulputate id, efficitur quis lectus.

In finibus lobortis ex ac tristique. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. <br/><br/> In hac habitasse platea dictumst. Nam tincidunt elit luctus quam rhoncus vehicula. In aliquam bibendum mi, a egestas ipsum porta id. In hac habitasse platea dictumst. Curabitur congue orci id libero aliquam ullamcorper. Praesent quis neque feugiat, elementum orci nec, luctus enim. In sed lorem vehicula, fermentum nunc et, scelerisque leo. Proin molestie risus non nulla ornare mattis in sed sem.

Quisque felis elit, sagittis ac tellus eu, porttitor sagittis lorem. Sed pharetra vehicula sapien, eget gravida augue tempus vel. Curabitur eu leo at nunc viverra placerat eleifend ut nisl. Vivamus tincidunt leo a hendrerit sodales. Nunc consequat vulputate aliquam. Vestibulum tempor venenatis risus. Vestibulum viverra auctor magna vel pharetra. Vivamus blandit felis eget aliquam volutpat. Aenean ultrices diam ligula, vitae pellentesque nunc sollicitudin sed. Aliquam erat volutpat. Donec posuere neque sollicitudin rhoncus cursus. Pellentesque congue a nisl ac bibendum. Nullam laoreet ante non elementum congue.

Duis eget diam congue, placerat tellus at, faucibus erat. Curabitur et imperdiet nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non fringilla enim. Aenean in augue vel magna accumsan molestie. Pellentesque mattis tortor sed felis dignissim, id porttitor arcu volutpat. Aenean nec pretium arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam pellentesque finibus varius. Nullam blandit velit viverra diam fringilla, pretium accumsan purus porta. Praesent pulvinar erat id purus ullamcorper hendrerit.

Integer mauris nulla, aliquam sed mollis dignissim, suscipit vel urna. Nullam rutrum elit sit amet diam aliquam sollicitudin. <br/> <br/>In eu velit sed nibh sagittis pulvinar in in risus. Morbi ac fermentum magna. Etiam a accumsan tortor, vitae congue sem. Proin cursus sit amet nisl sed egestas. Fusce gravida tellus eu tincidunt convallis. Nullam imperdiet dolor velit, vitae tincidunt lacus auctor eget. Quisque sed pretium orci. Nullam a ex in est volutpat euismod at quis nunc.

Nulla dui est, ultricies sed aliquet id, pretium ac tortor. Proin molestie sodales orci, nec tincidunt eros rutrum quis. Curabitur rhoncus, odio finibus lacinia facilisis, leo dolor volutpat massa, ut pulvinar leo quam in mauris. Cras ligula dolor, imperdiet tincidunt sagittis sit amet, accumsan at tortor. Praesent hendrerit in enim vitae iaculis. Maecenas consequat efficitur velit vitae tincidunt. Etiam bibendum nisi vitae turpis rhoncus, vitae consequat velit euismod. Ut venenatis, diam in vulputate vestibulum, ligula eros auctor justo, fringilla auctor lectus justo vitae quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus auctor dolor quam, id porta nisi convallis consectetur. Praesent cursus leo arcu, sit amet elementum neque lobortis eu. Proin lobortis laoreet ligula in dictum. Curabitur sit amet nunc eget turpis efficitur sagittis at in lectus.

Etiam elementum cursus urna at porta.<br/><br/> Proin eu rhoncus lectus. Duis porta vel libero in iaculis. Mauris pretium risus ut magna vestibulum dictum. Duis mattis magna at dolor ullamcorper bibendum. Sed condimentum vel libero sit amet mollis. Integer et tristique augue. Vivamus sed tempor dui. Suspendisse ut mi posuere sapien tempus molestie sed sed libero. Ut id aliquam urna, nec fermentum lorem. Suspendisse faucibus viverra enim id faucibus. Curabitur eu purus suscipit, varius quam mollis, cursus lacus. Nam euismod fermentum lectus id venenatis. Donec velit purus, egestas eget ex quis, suscipit egestas nisi.

Quisque diam odio, facilisis non nunc eu, volutpat pulvinar velit. Donec purus mi, suscipit vel diam id, malesuada commodo lectus.<br/><br/> Aenean aliquet diam eu erat commodo consequat. Etiam suscipit, metus vel congue luctus, sem velit vehicula neque, congue fermentum libero dui a massa. Maecenas ligula quam, fringilla interdum mauris sit amet, posuere cursus diam. Fusce placerat diam sed semper ullamcorper. Phasellus eget maximus augue. Ut vitae venenatis ipsum. Nunc semper gravida erat, ut aliquet purus semper non. Duis tempor imperdiet nisl, eget consequat tortor pulvinar vel. Proin elementum vitae massa et hendrerit. Nullam lacinia malesuada massa nec pellentesque. Proin diam arcu, scelerisque a sodales eget, posuere at sem. Donec varius vulputate nunc nec commodo. Aliquam in erat mauris. Donec pharetra mauris purus.

Aliquam eu urna malesuada, aliquet ligula at, eleifend metus. In vestibulum velit sapien, id tincidunt lorem volutpat ac. Donec sed metus consequat, pharetra ipsum a, cursus ipsum. Donec semper quam id ligula fringilla convallis. In tincidunt a arcu ac pharetra. Nunc sollicitudin convallis augue, nec commodo dolor viverra id. Praesent malesuada risus a ipsum bibendum euismod. Ut ornare justo vitae odio tempus congue. Fusce maximus justo vel nisl aliquet, at auctor massa cursus. Etiam eget consequat diam. Sed ac rhoncus urna. Sed hendrerit nibh aliquam nulla dapibus rutrum. Praesent eget posuere odio. Nulla dignissim eleifend odio vel mollis. Sed cursus lorem suscipit, feugiat ligula eu, aliquam ante. Ut hendrerit ante eu viverra feugiat.
        
        </div>
    )
}

export {Historia};